[build]
  command = "cd backend/flaskr && pip install -r requirements.txt && cd ../.. && npm install && npm run build"
  publish = "frontend/real-estate/dist"

[[redirects]]
  from = "/*"
  to = "http://localhost:5000/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
